modLoader="javafml" 
loaderVersion="[30,)" #mandatory (28 is current forge version)
authors="Peerius" 

[[mods]] #mandatory
modId="deepaffection" #mandatory
version="0.2.1" #mandatory
displayName="DeepAffection Mod" #mandatory
description='''
A mod adding some stuff 
'''


[[dependencies.deepaffection]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[30,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.deepaffection]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
